name: gsplat

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pipdeptree
  - bash>=4
  - wget

  # Utilities
  - rclone
  - tree
  - tqdm
  - matplotlib

  # Build tools
  - cmake
  - ninja

  # Scientific stack
  - "numpy<2"
  - scipy

  # IO / Media
  - openimageio
  - ffmpeg
  - imageio
  - imageio-ffmpeg
  - rasterio
  - libgdal-jp2openjpeg

  # Geometry / SfM
  - colmap=3.8
  - faiss-cpu
  - plyfile
  - laspy
  - pdal

  # Graphics
  - glew
  - qt-main

  - pip:
      - pycolmap
      - ultralytics
      - nerfstudio
      - gsplat
      - fpsample
      - pyglet
      - git+https://github.com/cvg/Hierarchical-Localization.git@v1.4
      - git+https://github.com/facebookresearch/segment-anything.git
